import { createService, deleteService, toggleService } from "@/app/dashboard/actions";
import { requireWorkspace } from "@/modules/tenancy/workspace";
import { formatCurrency } from "@/lib/format";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Service } from "@/lib/types";

export default async function ServicesPage() {
  const workspace = await requireWorkspace();
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase.from("services").select("*").eq("organization_id", workspace.organization.id).order("created_at");
  const services = (data ?? []) as Service[];
  return <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_23rem]"><section><p className="text-sm font-semibold text-emerald-700">Serviços</p><h1 className="mt-1 text-3xl font-bold tracking-tight">O que você oferece?</h1><p className="mt-2 text-stone-600">Somente serviços ativos aparecem para seus clientes.</p><div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm">{services.length === 0 ? <p className="p-6 text-sm text-stone-500">Você ainda não cadastrou nenhum serviço.</p> : <div className="divide-y divide-stone-100">{services.map((service) => <article className="flex flex-wrap items-center justify-between gap-4 p-5" key={service.id}><div><div className="flex items-center gap-2"><h2 className="font-semibold">{service.name}</h2>{!service.is_active && <span className="rounded-full bg-stone-100 px-2 py-0.5 text-xs font-medium text-stone-500">Pausado</span>}</div><p className="mt-1 text-sm text-stone-500">{service.duration_minutes} min · {formatCurrency(service.price_cents)}</p></div><div className="flex gap-2"><form action={toggleService}><input type="hidden" name="service_id" value={service.id} /><input type="hidden" name="is_active" value={String(!service.is_active)} /><button className="rounded-lg border border-stone-200 px-3 py-2 text-sm font-semibold text-stone-700">{service.is_active ? "Pausar" : "Ativar"}</button></form><form action={deleteService}><input type="hidden" name="service_id" value={service.id} /><button className="rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Excluir</button></form></div></article>)}</div>}</div></section>
    <aside className="h-fit rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Novo serviço</h2><form action={createService} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Nome<input required name="name" minLength={2} placeholder="Corte masculino" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-semibold">Duração<select name="duration" defaultValue="30" className="mt-1.5 w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-emerald-600">{[15,30,45,60,75,90,120].map((minutes) => <option key={minutes} value={minutes}>{minutes} min</option>)}</select></label><label className="block text-sm font-semibold">Preço<input required name="price" inputMode="decimal" placeholder="45,00" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label></div><button className="w-full rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white hover:bg-emerald-700">Adicionar serviço</button></form></aside></div>;
}
