import { cancelBooking, createBlock, deleteBlock } from "@/app/dashboard/actions";
import { ActionForm } from "@/components/action-form";
import { requireWorkspace } from "@/modules/tenancy/workspace";
import { formatCurrency, formatDateTime } from "@/lib/format";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { CalendarEvent } from "@/lib/types";

export default async function AgendaPage() {
  const workspace = await requireWorkspace();
  const supabase = await createSupabaseServerClient();
  const retentionStart = new Date();
  retentionStart.setDate(retentionStart.getDate() - 30);
  const { data } = await supabase.from("calendar_events").select("*").eq("organization_id", workspace.organization.id).eq("location_id", workspace.location.id).gte("ends_at", retentionStart.toISOString()).order("starts_at").limit(100);
  const events = (data ?? []) as CalendarEvent[];
  const defaultDate = new Intl.DateTimeFormat("en-CA", { timeZone: workspace.location.time_zone }).format(new Date());
  return <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_23rem]">
    <section><p className="text-sm font-semibold text-emerald-700">Agenda</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Próximos horários</h1><p className="mt-2 text-stone-600">Atendimentos, cancelamentos e períodos bloqueados.</p><div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm">{events.length === 0 ? <p className="p-6 text-sm text-stone-500">Nenhum compromisso futuro. Quando um cliente agendar, ele aparecerá aqui.</p> : <div className="divide-y divide-stone-100">{events.map((event) => <article className={`flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between ${event.status === "cancelled" ? "bg-stone-50/80 opacity-75" : ""}`} key={event.id}><div><div className="flex items-center gap-2"><h2 className="font-semibold">{event.event_type === "booking" ? event.service_name : event.title}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${event.status === "cancelled" ? "bg-stone-200 text-stone-600" : event.event_type === "booking" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{event.status === "cancelled" ? "Cancelado" : event.event_type === "booking" ? "Agendado" : "Bloqueado"}</span></div><p className="mt-1 text-sm text-stone-600">{event.event_type === "booking" ? `${event.customer_name} · ${event.customer_phone}` : "Indisponível para novos agendamentos"}</p><p className="mt-1 text-sm text-stone-500">{formatDateTime(event.starts_at, workspace.location.time_zone)} · {event.service_price_cents !== null ? formatCurrency(event.service_price_cents) : ""}</p></div>{event.status === "confirmed" && event.event_type === "booking" && <ActionForm action={cancelBooking} className="flex gap-2"><input type="hidden" name="event_id" value={event.id} /><input name="reason" className="min-w-0 rounded-lg border border-stone-200 px-2 py-2 text-sm" placeholder="Motivo (opcional)" /><button className="rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Cancelar</button></ActionForm>}{event.event_type === "block" && event.status === "confirmed" && <ActionForm action={deleteBlock}><input type="hidden" name="event_id" value={event.id} /><button className="rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Remover bloqueio</button></ActionForm>}</article>)}</div>}</div></section>
    <aside className="h-fit rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Bloquear período</h2><p className="mt-1 text-sm leading-6 text-stone-500">Use para pausa, compromisso ou indisponibilidade.</p><ActionForm action={createBlock} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Motivo <span className="font-normal text-stone-500">(opcional)</span><input name="title" placeholder="Ex.: Almoço" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label><label className="block text-sm font-semibold">Data<input required type="date" name="date" defaultValue={defaultDate} className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-semibold">Início<input required type="time" name="starts_at" defaultValue="12:00" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label><label className="block text-sm font-semibold">Fim<input required type="time" name="ends_at" defaultValue="13:00" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label></div><button className="w-full rounded-xl border border-stone-300 px-4 py-2.5 font-semibold text-stone-700 hover:bg-stone-50">Bloquear horário</button></ActionForm></aside>
  </div>;
}
