"use client";

import { useState } from "react";
import { ActionForm, type ActionState } from "@/components/action-form";

const days = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
type Props = { defaultDate: string; action: (state: ActionState, formData: FormData) => Promise<ActionState> };

export function AvailabilityBlockForm({ defaultDate, action }: Props) {
  const [mode, setMode] = useState("single");
  return <ActionForm action={action} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Tipo de bloqueio<select name="mode" value={mode} onChange={(event) => setMode(event.target.value)} className="mt-1.5 w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 outline-none focus:border-emerald-600"><option value="single">Data e horário específicos</option><option value="weekly">Pausa semanal</option><option value="range">Período completo (férias)</option></select></label><label className="block text-sm font-semibold">Motivo <span className="font-normal text-stone-500">(opcional)</span><input name="title" placeholder={mode === "weekly" ? "Ex.: Almoço" : mode === "range" ? "Ex.: Férias" : "Ex.: Compromisso"} className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label>{mode === "weekly" ? <fieldset><legend className="text-sm font-semibold">Dias da semana</legend><div className="mt-2 grid grid-cols-4 gap-2">{days.map((day, index) => <label className="flex items-center gap-2 rounded-lg border border-stone-200 px-2 py-2 text-sm" key={day}><input type="checkbox" name="week_days" value={index} className="accent-emerald-600" />{day}</label>)}</div></fieldset> : <div className="grid grid-cols-2 gap-3"><label className="block text-sm font-semibold">{mode === "range" ? "Data inicial" : "Data"}<input required type="date" name="start_date" defaultValue={defaultDate} className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label>{mode === "range" && <label className="block text-sm font-semibold">Data final<input required type="date" name="end_date" defaultValue={defaultDate} className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label>}</div>}{mode !== "range" && <div className="grid grid-cols-2 gap-3"><label className="block text-sm font-semibold">Início<input required type="time" name="starts_at" defaultValue="12:00" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label><label className="block text-sm font-semibold">Fim<input required type="time" name="ends_at" defaultValue="13:00" className="mt-1.5 w-full rounded-xl border border-stone-300 px-3 py-2.5 outline-none focus:border-emerald-600" /></label></div>}{mode === "range" && <p className="rounded-xl bg-amber-50 px-3 py-2 text-sm text-amber-900">Durante todo o período não haverá horários disponíveis. O sistema avisará se existir atendimento futuro em conflito.</p>}<button className="w-full rounded-xl border border-stone-300 px-4 py-2.5 font-semibold text-stone-700 hover:bg-stone-50">Criar bloqueio</button></ActionForm>;
}
